# -*- coding: utf-8 -*-            
# @Time : 2024/9/12 17:20
# @Author : wangfaqi
# @File ： lagrange_custom_nominal.py
#
# Parameters below are adapted to TestModelAssembly in
# 4825214f-3982-4a39-8cec-f5cc23219827.wbt.
#
# Important limitation:
# The original model replaces each five-bar leg with one equivalent rigid leg.
# A WBT snapshot provides exact mass/inertia data at only one configuration, so
# the equivalent leg COM and inertia used here are nominal-pose estimates.  The
# direct WBT parameters (wheel radius, masses and inertias) are exact; the
# equivalent-leg parameters must later be fitted over the intended L0 range.
#
# K output order is [T_left_wheel, T_right_wheel, T_left_leg, T_right_leg].
# The user's Webots wheel motors/sensors are reversed relative to these corrected
# coordinates, so the controller must apply -T_left_wheel and -T_right_wheel to
# the raw Webots wheel motors.  Leg torques continue through Mat_JRM([F, T_p]).

import numpy as np
import scipy


# Direct physical parameters extracted from the current WBT.
MODEL_PARAMETERS = {
    "wheel_radius": 0.05995,
    # Half the distance between the left and right wheel joint axes.
    "half_track": 0.227605,
    "body_mass": 4.259101,
    "left_wheel_mass": 0.402228,
    "right_wheel_mass": 0.399779,
    "left_leg_mass": 1.346652,
    "right_leg_mass": 1.348037,
    # Wheel axial inertia: local Izz maps to the global wheel axis.
    "left_wheel_axial_inertia": 0.0005388067,
    "right_wheel_axial_inertia": 0.0005387982,
    # Body pitch inertia about global Y.
    "body_pitch_inertia": 0.008696656,
    # First-order intrinsic yaw inertia estimate. Translational yaw inertia of
    # the side masses is already generated by the coordinate transformation.
    "yaw_intrinsic_inertia": 0.01544389598,
    "gravity": 9.81,
}


# Nominal equivalent-leg values extracted at the WBT reset pose.
NOMINAL_L0 = 0.159685
LEFT_COM_FROM_WHEEL_RATIO = 0.8943352147
RIGHT_COM_FROM_WHEEL_RATIO = 0.8858397316
LEFT_LEG_PITCH_INERTIA_NOMINAL = 0.00976296197
RIGHT_LEG_PITCH_INERTIA_NOMINAL = 0.01039904621


def equivalent_leg_parameters(ll, lr):
    """Return first-order equivalent-leg parameters.

    ll/lr are virtual leg lengths in metres.  COM ratios and pitch inertias are
    nominal-pose estimates.  Replace this function with fitted polynomials once
    several WBT poses over the working leg-length range have been measured.
    """
    if ll <= 0.0 or lr <= 0.0:
        raise ValueError("virtual leg lengths must be positive")

    l_wl = LEFT_COM_FROM_WHEEL_RATIO * ll
    l_wr = RIGHT_COM_FROM_WHEEL_RATIO * lr
    l_bl = ll - l_wl
    l_br = lr - l_wr

    # Keep the measured nominal inertias constant until multi-pose fitting is
    # available.  This is safer than silently reusing the open-source fit.
    I_ll = LEFT_LEG_PITCH_INERTIA_NOMINAL
    I_lr = RIGHT_LEG_PITCH_INERTIA_NOMINAL
    return l_wl, l_wr, l_bl, l_br, I_ll, I_lr


def K(ll, lr, q1, q2, q3, q4, q5, q6, q7, q8, q9, q10,
      r1, r2, r3, r4, return_matrices=False):
    # 赋值
    R_w = MODEL_PARAMETERS["wheel_radius"]
    R_l = MODEL_PARAMETERS["half_track"]
    m_b = MODEL_PARAMETERS["body_mass"]
    m_wl = MODEL_PARAMETERS["left_wheel_mass"]
    m_wr = MODEL_PARAMETERS["right_wheel_mass"]
    m_ll = MODEL_PARAMETERS["left_leg_mass"]
    m_lr = MODEL_PARAMETERS["right_leg_mass"]
    I_wl = MODEL_PARAMETERS["left_wheel_axial_inertia"]
    I_wr = MODEL_PARAMETERS["right_wheel_axial_inertia"]
    I_b = MODEL_PARAMETERS["body_pitch_inertia"]
    I_z = MODEL_PARAMETERS["yaw_intrinsic_inertia"]
    g = MODEL_PARAMETERS["gravity"]

    l_l, l_r = ll, lr
    l_wl, l_wr, l_bl, l_br, I_ll, I_lr = equivalent_leg_parameters(ll, lr)

    # 被注释部分为采用拉式方程建立机器人状态方程的符号运算过程

    # t = symbols('t')
    #
    # theta_wl = Function('theta_wl')
    # theta_wr = Function('theta_wr')
    # theta_ll = Function('theta_ll')
    # theta_lr = Function('theta_lr')
    # theta_b = Function('theta_b')
    #
    # R_w, R_l, l_l, l_r, l_wl, l_wr, l_bl, l_br, l_c, m_w, m_l, m_b, I_w, I_ll, I_lr, I_b, I_z, g \
    #     = symbols('R_w,R_l,l_l,l_r,l_wl,l_wr,l_bl,l_br,l_c,m_w,m_l,m_b,I_w,I_ll,I_lr,I_b,I_z,g')
    #
    # s = R_w / 2 * (theta_wl(t) + theta_wr(t))
    # h_b = l_l * cos(theta_ll(t)) + l_r * cos(theta_lr(t))
    # s_ll = R_w * theta_wl(t) + l_wl * sin(theta_ll(t))
    # s_lr = R_w * theta_wr(t) + l_wr * sin(theta_lr(t))
    # h_ll = h_b - l_bl * cos(theta_ll(t))
    # h_lr = h_b - l_br * cos(theta_lr(t))
    #
    # # Equations = [Eq(R_w*theta_wl(t)-s_b+R_l*fai+l_l*sin(theta_ll(t)),0),
    # #              Eq(R_w*theta_wr(t)-s_b-R_l*fai+l_r*sin(theta_lr(t)),0)]
    # #
    # # solutions =solve(Equations,(fai,s_b))
    # # print(solutions)
    #
    # fai = -R_w * theta_wl(t) / (2 * R_l) + R_w * theta_wr(t) / (2 * R_l) - l_l * sin(theta_ll(t)) / (
    #         2 * R_l) + l_r * sin(
    #     theta_lr(t)) / (2 * R_l)
    # s_b = R_w * theta_wl(t) / 2 + R_w * theta_wr(t) / 2 + l_l * sin(theta_ll(t)) / 2 + l_r * sin(theta_lr(t)) / 2
    #
    # dot_s = diff(s, t)
    # ddot_s = diff(dot_s, t)
    #
    # dot_fai = diff(fai, t)
    # ddot_fai = diff(dot_fai, t)
    #
    # dot_s_b = diff(s_b, t)
    # ddot_s_b = diff(dot_s_b, t)
    #
    # dot_h_b = diff(h_b, t)
    # ddot_h_b = diff(dot_h_b, t)
    #
    # dot_s_ll = diff(s_ll, t)
    # dot_s_lr = diff(s_lr, t)
    # ddot_s_ll = diff(dot_s_ll, t)
    # ddot_s_lr = diff(dot_s_lr, t)
    #
    # dot_h_ll = diff(h_ll, t)
    # dot_h_lr = diff(h_lr, t)
    # ddot_h_ll = diff(dot_h_ll, t)
    # ddot_h_lr = diff(dot_h_lr, t)
    #
    # # linearization
    # # dot_s = R_w * (Derivative(theta_wl(t), t) + Derivative(theta_wr(t), t)) / 2
    # # ddot_s = R_w * (Derivative(theta_wl(t), (t, 2)) + Derivative(theta_wr(t), (t, 2))) / 2
    # #
    # # dot_fai = -R_w * Derivative(theta_wl(t), t) / (2 * R_l) + R_w * Derivative(theta_wr(t), t) / (
    # #         2 * R_l) - l_l * Derivative(theta_ll(t), t) / (2 * R_l) + l_r * Derivative(theta_lr(t), t) / (2 * R_l)
    # # ddot_fai = -R_w * Derivative(theta_wl(t), (t, 2)) / (2 * R_l) + R_w * Derivative(theta_wr(t), (t, 2)) / (
    # #         2 * R_l) - l_l * Derivative(theta_ll(t), (t, 2)) / (2 * R_l) + l_r * Derivative(theta_lr(t), (t, 2)) / (
    # #                    2 * R_l)
    # #
    # # dot_s_b = R_w * Derivative(theta_wl(t), t) / 2 + R_w * Derivative(theta_wr(t), t) / 2 + l_l * Derivative(
    # #     theta_ll(t),
    # #     t) / 2 + l_r * Derivative(
    # #     theta_lr(t), t) / 2
    # # ddot_s_b = R_w * Derivative(theta_wl(t), (t, 2)) / 2 + R_w * Derivative(theta_wr(t), (t, 2)) / 2 + l_l * Derivative(
    # #     theta_ll(t), (t, 2)) / 2 + l_r * Derivative(theta_lr(t), (t, 2)) / 2
    # #
    # # dot_h_b = 0
    # # ddot_h_b = 0
    # #
    # # dot_s_ll = R_w * Derivative(theta_wl(t), t) + l_wl * Derivative(theta_ll(t), t)
    # # dot_s_lr = R_w * Derivative(theta_wr(t), t) + l_wr * Derivative(theta_lr(t), t)
    # # ddot_s_ll = R_w * Derivative(theta_wl(t), (t, 2)) + l_wl * Derivative(theta_ll(t), (t, 2))
    # # ddot_s_lr = R_w * Derivative(theta_wr(t), (t, 2)) + l_wr * Derivative(theta_lr(t), (t, 2))
    # #
    # # dot_h_ll = 0
    # # dot_h_lr = 0
    # # ddot_h_ll = 0
    # # ddot_h_lr = 0
    #
    # T_w = m_w*R_w*R_w*(Derivative(theta_wl(t), t)**2+Derivative(theta_wr(t), t)**2)/2
    # T_1 = m_l*(dot_s_ll**2+dot_h_ll**2)/2+m_l*(dot_s_lr**2+dot_h_lr**2)/2
    # T_2 = m_b*(dot_s_b**2+dot_h_b**2)/2
    # Ro_w = I_w*(Derivative(theta_wl(t), t)**2+Derivative(theta_wr(t), t)**2)/2
    # Ro_1 = (I_ll*Derivative(theta_ll(t),t)**2 + I_lr*Derivative(theta_lr(t),t)**2)/2
    # Ro_2 = (I_b*Derivative(theta_b(t),t)**2)/2
    # Ro_3 = (I_z*dot_fai**2)/2
    # U = m_l*g*l_wl*cos(theta_ll(t))+m_l*g*l_wr*cos(theta_lr(t))+m_b*g*(l_l*cos(theta_ll(t))/2+l_r*cos(theta_lr(t))/2)
    # L = T_w+T_1+T_2+Ro_w+Ro_1+Ro_2+Ro_3-U
    #
    # pL_pdtheta_wl = diff(L,diff(theta_wl(t),t))
    # pL_pdtheta_wr = diff(L,diff(theta_wr(t),t))
    # pL_pdtheta_ll = diff(L,diff(theta_ll(t),t))
    # pL_pdtheta_lr = diff(L,diff(theta_lr(t),t))
    # pL_pdtheta_b = diff(L,diff(theta_b(t),t))
    #
    #
    # pL_ptheta_wl = diff(L,theta_wl(t))
    # pL_ptheta_wr = diff(L,theta_wr(t))
    # pL_ptheta_ll = diff(L,theta_ll(t))
    # pL_ptheta_lr = diff(L,theta_lr(t))
    # pL_ptheta_b = diff(L,theta_b(t))
    #
    # ddt_pL_pdtheta_wl = diff(pL_pdtheta_wl,t)
    # ddt_pL_pdtheta_wr = diff(pL_pdtheta_wr,t)
    # ddt_pL_pdtheta_ll = diff(pL_pdtheta_ll,t)
    # ddt_pL_pdtheta_lr = diff(pL_pdtheta_lr,t)
    # ddt_pL_pdtheta_b = diff(pL_pdtheta_b,t)
    #
    # LARGE = [ddt_pL_pdtheta_wl - pL_ptheta_wl,
    #          ddt_pL_pdtheta_wr - pL_ptheta_wr,
    #          ddt_pL_pdtheta_ll - pL_ptheta_ll,
    #          ddt_pL_pdtheta_lr - pL_ptheta_lr,
    #          ddt_pL_pdtheta_b - pL_ptheta_b]
    #
    #
    # M = Matrix([[0,0,0,0,0],
    #             [0,0,0,0,0],
    #             [0,0,0,0,0],
    #             [0,0,0,0,0],
    #             [0,0,0,0,0]])
    #
    # for i in range(5):
    #     M[5*i+0] = diff(LARGE[i],diff(diff(theta_wl(t))))
    #     M[5*i+1] = diff(LARGE[i],diff(diff(theta_wr(t))))
    #     M[5*i+2] = diff(LARGE[i],diff(diff(theta_ll(t))))
    #     M[5*i+3] = diff(LARGE[i],diff(diff(theta_lr(t))))
    #     M[5*i+4] = diff(LARGE[i],diff(diff(theta_b(t))))
    #
    # N = Matrix([[0],
    #             [0],
    #             [0],
    #             [0],
    #             [0]])
    #
    # for i in range(5):
    #     N[i] = LARGE[i] - M[5*i+0]*diff(diff(theta_wl(t))) - M[5*i+1]*diff(diff(theta_wr(t))) - M[5*i+2]*diff(diff(theta_ll(t))) \
    #          - M[5*i+3]*diff(diff(theta_lr(t))) - M[5*i+4]*diff(diff(theta_b(t)))
    #     print(latex(N[i]))
    #
    # print(latex(M))
    #
    # E = Matrix([[1,0,0,0],
    #             [0,1,0,0],
    #             [-1,0,-1,0],
    #             [0,-1,0,-1],
    #             [0,0,1,1]])
    #
    inv_Tr = np.matrix([[R_w / 2, R_w / 2, 0, 0, 0],
                        [-R_w / (2 * R_l), R_w / (2 * R_l), -l_l / (2 * R_l), l_r / (2 * R_l), 0],
                        [0, 0, 1, 0, 0],
                        [0, 0, 0, 1, 0],
                        [0, 0, 0, 0, 1]])
    #
    #
    # def MatLinear(A):
    #     return eval(str(A).replace('Derivative(theta_wl(t), t)**2','0').replace('Derivative(theta_wr(t), t)**2','0').replace('Derivative(theta_ll(t), t)**2','0').replace('Derivative(theta_lr(t), t)**2','0')
    #                 .replace('Derivative(theta_wl(t), (t, 2))', '0').replace('Derivative(theta_wr(t), (t, 2))', '0').replace('Derivative(theta_ll(t), (t, 2))', '0').replace('Derivative(theta_lr(t), (t, 2))', '0')
    #                 .replace('cos(theta_ll(t))','1').replace('cos(theta_lr(t))','1').replace('sin(theta_ll(t))','theta_ll(t)').replace('sin(theta_lr(t))','theta_lr(t)')
    #                 .replace('theta_ll(t)**2','0').replace('theta_lr(t)**2','0')
    #                 .replace('l_br*theta_lr(t) - l_r*theta_lr(t)','0').replace('l_bl*theta_ll(t) - l_l*theta_ll(t)','0')
    #                 .replace('2*l_br*theta_lr(t) - 2*l_r*theta_lr(t)', '0').replace('2*l_bl*theta_ll(t) - 2*l_l*theta_ll(t)', '0')
    #                 .replace('theta_ll(t)*theta_lr(t)', '0'))
    #
    #
    # print((latex(MatLinear(M))))
    # print(MatLinear(M))
    # print(MatLinear(N[0]))
    # print(MatLinear(N[1]))
    # print(MatLinear(N[2]))
    # print(MatLinear(N[3]))
    # print(MatLinear(N[4]))

    Mat_M = np.matrix([[I_wl + I_z * R_w ** 2 / (4 * R_l ** 2) + R_w ** 2 * m_b / 4 + R_w ** 2 * m_ll + R_w ** 2 * m_wl,
                        -I_z * R_w ** 2 / (4 * R_l ** 2) + R_w ** 2 * m_b / 4, I_z * R_w * l_l / (4 * R_l ** 2) + R_w * l_l * m_b / 4 + R_w * l_wl * m_ll,
                        -I_z * R_w * l_r / (4 * R_l ** 2) + R_w * l_r * m_b / 4, 0],
                       [-I_z * R_w ** 2 / (4 * R_l ** 2) + R_w ** 2 * m_b / 4,
                        I_wr + I_z * R_w ** 2 / (4 * R_l ** 2) + R_w ** 2 * m_b / 4 + R_w ** 2 * m_lr + R_w ** 2 * m_wr,
                        -I_z * R_w * l_l / (4 * R_l ** 2) + R_w * l_l * m_b / 4, I_z * R_w * l_r / (4 * R_l ** 2) + R_w * l_r * m_b / 4 + R_w * l_wr * m_lr, 0],
                       [I_z * R_w * l_l / (4 * R_l ** 2) + R_w * l_l * m_b / 4 + R_w * l_wl * m_ll, -I_z * R_w * l_l / (4 * R_l ** 2) + R_w * l_l * m_b / 4,
                        I_ll + I_z * l_l ** 2 / (4 * R_l ** 2) + l_l ** 2 * m_b / 4 + l_wl ** 2 * m_ll, -I_z * l_l * l_r / (4 * R_l ** 2) + l_l * l_r * m_b / 4,
                        0],
                       [-I_z * R_w * l_r / (4 * R_l ** 2) + R_w * l_r * m_b / 4, I_z * R_w * l_r / (4 * R_l ** 2) + R_w * l_r * m_b / 4 + R_w * l_wr * m_lr,
                        -I_z * l_l * l_r / (4 * R_l ** 2) + l_l * l_r * m_b / 4, I_lr + I_z * l_r ** 2 / (4 * R_l ** 2) + l_r ** 2 * m_b / 4 + l_wr ** 2 * m_lr,
                        0],
                       [0, 0, 0, 0, I_b]])

    Mat_N = np.matrix([[0, 0, 0, 0, 0],
                       [0, 0, 0, 0, 0],
                       [0, 0, -g * l_l * m_b / 2 - g * l_wl * m_ll, 0, 0],
                       [0, 0, 0, -g * l_r * m_b / 2 - g * l_wr * m_lr, 0],
                       [0, 0, 0, 0, 0], ])

    Mat_O = np.zeros((5, 5))
    Mat_O4 = np.zeros((5, 4))
    Mat_I = np.identity(5)

    #Mat_E的正负号需要根据自己所建立lagrange方程的符号做对应的调整
    Mat_E = np.matrix([[1, 0, 0, 0],
                       [0, 1, 0, 0],
                       [-1, 0, 1, 0],
                       [0, -1, 0, 1],
                       [0, 0, -1, -1]])

    # print(Mat_O, Mat_I)

    MAT_M = np.matrix(np.block([[Mat_I, Mat_O], [Mat_O, Mat_M]]))
    MAT_N = np.matrix(np.block([[Mat_O, -Mat_I], [Mat_N, Mat_O]]))
    MAT_E = np.matrix(np.block([[Mat_O4], [Mat_E]]))
    MAT_T1 = np.matrix(np.block([[inv_Tr, Mat_O], [Mat_O, inv_Tr]]))
    MAT_T2 = np.matrix([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
                        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
                        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
                        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
                        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])
    MAT_T = MAT_T2 * MAT_T1

    # print(MAT_M)
    # print(MAT_E)

    # Mat_M * ddot_q + Mat_N * q = MAT_E * tao
    # MAT_M * MAT_T.I * dot_Q + MAT_N * MAT_T.I * Q = MAT_E * tao

    ## 在这里补充一下q和Q的含义
    ## q = np.matrix([[theta_wl],[theta_wr],[theta_ll],[theta_lr],[theta_b]])
    ## Q = np.matrix([[s],[dot_s],[fai],[dot_fai],[theta_ll],[dot_theta_ll],[theta_lr],[dot_theta_lr],[theta_b],[dot_theta_b]])
    ## 从q到Q进行了坐标变换，两个轮的角度theta_wl和theta_wr变换为机器人整体位移s和航向角fai，MAT_T就是变换矩阵，同时需要注意维度变化，由5维q变为10维Q。


    # MAT_M * MAT_T.I * dot_Q = - MAT_N * MAT_T.I * Q + MAT_E * tao
    # dot_Q = - (MAT_M * MAT_T.I).I * MAT_N * MAT_T.I * Q + (MAT_M * MAT_T.I).I * MAT_E * tao
    # dot_Q = - MAT_T * MAT_M.I * MAT_N * MAT_T.I * Q + MAT_T * MAT_M.I * MAT_E * tao

    MAT_A = - MAT_T * MAT_M.I * MAT_N * MAT_T.I
    MAT_B = MAT_T * MAT_M.I * MAT_E
    

    # print(MAT_A)
    # print(MAT_B)

    QQ = np.zeros((10, 10))

    QQ[0][0] = q1
    QQ[1][1] = q2
    QQ[2][2] = q3
    QQ[3][3] = q4
    QQ[4][4] = q5
    QQ[5][5] = q6
    QQ[6][6] = q7
    QQ[7][7] = q8
    QQ[8][8] = q9
    QQ[9][9] = q10

    R = np.matrix([[r1, 0, 0, 0],
                   [0, r2, 0, 0],
                   [0, 0, r3, 0],
                   [0, 0, 0, r4]])

    # 连续
    P = scipy.linalg.solve_continuous_are(MAT_A, MAT_B, QQ, R)
    K = R.I * MAT_B.T * P

    # 当然也可以使用离散LQR计算K值，在仿真里都差不多，这里附上有关代码
    # def K_discrete_lqr(A, B, Q, R):
    #     C = np.zeros((4, 10))
    #     D = np.zeros((4, 4))
    #     system_LIP = control.ss(A, B, C, D)
    #     system_dLIP = control.c2d(system_LIP, 0.01)
    #     # print(system_dLIP)
    #     MAT_dA = np.matrix(system_dLIP.A)
    #     MAT_dB = np.matrix(system_dLIP.B)
    #     P = scipy.linalg.solve_discrete_are(MAT_dA, MAT_dB, Q, R)
    #     K = (R + MAT_dB.T * P * MAT_dB).I * MAT_dB.T * P * MAT_dA
    #     return K

    if return_matrices:
        return K, MAT_A, MAT_B
    return K


if __name__ == "__main__":
    np.set_printoptions(precision = 4, suppress = True, linewidth = 300)

    # # print(A,B,Q,R)
    # a = time.time()
    # k1 = np.matrix(K_continuous_lqr(A, B, Q, R))
    k1, A1, B1 = K(
        0.25, 0.25,
        10, 5, 50, 1, 50, 1, 50, 1, 50, 1,
        1, 1, 1, 1,
        return_matrices=True,
    )
    print(k1)

    controllability = np.hstack(
        [np.linalg.matrix_power(A1, i) @ B1 for i in range(A1.shape[0])]
    )
    print("controllability rank =", np.linalg.matrix_rank(controllability))
    print(
        "max closed-loop real eigenvalue =",
        np.max(np.real(np.linalg.eigvals(A1 - B1 @ k1))),
    )

    for i in range(4):
        for j in range(10):
            print('K[{}] = {};'.format(10 * i + j, round(k1[i, j], 8)))
            # print(round(k1[i,j],8))
